-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort -rc --atomic src/getoffmylawn
        language: system
        types: [python]

    -   id: flake8
        name: Flake8
        entry: flake8
        language: system
        types: [python]

    -   id: black
        name: black
        entry: black
        language: system
        types: [python]

    -   id: debug-statements
        name: Check Debug Statements Absent (Python)
        description: Checks that debug statements (pdb, ipdb, pudb) are not imported on commit.
        entry: debug-statement-hook
        language: system
        types: [python]
        stages: [push]

    -   id: no-orm-alembic
        name: Check that ORM is not used in alembic migrations
        args: []
        entry: bash -c 'grep -ir "from sqlalchemy import orm" src/getoffmylawn/migrations/versions; test $? -eq 1'
        files: '(^.*src/getoffmylawn/migrations/versions/.*)'
        language: system
        stages: [commit]

    -   id: bandit
        name: Check for common security issues
        args: []
        entry: bandit -r src/getoffmylawn/ --skip B608 -x *tests*,src/getoffmylawn/scripts/populate.py
        language: system
        pass_filenames: false
        stages: [push]
